In [1]:
import pandas as pd
import torch

from copy import deepcopy
from sklearn import tree, ensemble
from sklearn.metrics import confusion_matrix
from matplotlib import pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

from common_test import *

In [2]:
df_mimic, df_eicu = get_datasets()

In [3]:
def get_feature_importance(classifier, columns=new_columns47):
    feature_importance = [(idx, importance, columns[idx]) for idx, importance in enumerate(classifier.feature_importances_)]
    feature_importance = pd.DataFrame(feature_importance, columns=['featureNum', 'importance', 'featureName'])
    feature_importance = feature_importance.sort_values('importance', ascending=False)
    return feature_importance

In [4]:
def get_DTClassifier(dataframe, label_column):
    s = np.asarray(dataframe[new_columns47])
    target = np.asarray(dataframe[label_column])
    
#     clf = tree.DecisionTreeClassifier()
    clf = ensemble.RandomForestClassifier(n_estimators=100)
    clf = clf.fit(s, target)
    fi = get_feature_importance(clf)
    return clf, fi

In [5]:
clf_phys_iv_mimic, fi_phys_iv_mimic = get_DTClassifier(df_mimic, 'phys_iv')
clf_rein_iv_mimic, fi_rein_iv_mimic = get_DTClassifier(df_mimic, 'rein_iv')

clf_phys_vaso_mimic, fi_phys_vaso_mimic = get_DTClassifier(df_mimic, 'phys_vaso')
clf_rein_vaso_mimic, fi_rein_vaso_mimic = get_DTClassifier(df_mimic, 'rein_vaso')

clf_phys_iv_eicu, fi_phys_iv_eicu = get_DTClassifier(df_eicu, 'phys_iv')
clf_rein_iv_eicu, fi_rein_iv_eicu = get_DTClassifier(df_eicu, 'rein_iv')

clf_phys_vaso_eicu, fi_phys_vaso_eicu = get_DTClassifier(df_eicu, 'phys_vaso')
clf_rein_vaso_eicu, fi_rein_vaso_eicu = get_DTClassifier(df_eicu, 'rein_vaso')

In [6]:
fi_phys_iv_mimic

    featureNum  importance        featureName
44          44    0.230474      previous_dose
43          43    0.050374        input_total
33          33    0.042474  cumulated_balance
46          46    0.034554     output_4hourly
45          45    0.034256       output_total
31          31    0.018591        Shock_Index
12          12    0.018221             Temp_C
7            7    0.017974                 HR
8            8    0.017959              SysBP
11          11    0.017768                 RR
9            9    0.017716             MeanBP
4            4    0.017699                age
22          22    0.017592    Platelets_count
20          20    0.017248                 Hb
10          10    0.017182              DiaBP
17          17    0.017107            Glucose
21          21    0.017051          WBC_count
37          37    0.016852                BUN
36          36    0.016825               SpO2
26          26    0.016418               paO2
5            5    0.016349          Weight_kg
23          23    0.016320                PTT
32          32    0.016093          PaO2_FiO2
19          19    0.016034            Calcium
24          24    0.015077                 PT
14          14    0.014966          Potassium
25          25    0.014887        Arterial_pH
38          38    0.014810         Creatinine
39          39    0.014799               SGOT
40          40    0.014748               SGPT
27          27    0.014701              paCO2
16          16    0.014562           Chloride
29          29    0.014506   Arterial_lactate
28          28    0.013942        Arterial_BE
13          13    0.013893             FiO2_1
15          15    0.013759             Sodium
30          30    0.013674               HCO3
18          18    0.013661          Magnesium
41          41    0.013417         Total_bili
2            2    0.012079           mechvent
34          34    0.011481               SOFA
6            6    0.011411                GCS
42          42    0.010739                INR
3            3    0.008385     prev_dose_vaso
35          35    0.005957               SIRS
1            1    0.002728       re_admission
0            0    0.002688             gender

In [7]:
fi_rein_iv_mimic

    featureNum  importance        featureName
44          44    0.078796      previous_dose
46          46    0.040937     output_4hourly
45          45    0.033724       output_total
33          33    0.032396  cumulated_balance
43          43    0.025859        input_total
37          37    0.023693                BUN
7            7    0.023383                 HR
31          31    0.023229        Shock_Index
10          10    0.023018              DiaBP
4            4    0.022976                age
12          12    0.022967             Temp_C
22          22    0.022892    Platelets_count
9            9    0.022813             MeanBP
17          17    0.022725            Glucose
11          11    0.022589                 RR
21          21    0.022306          WBC_count
8            8    0.022298              SysBP
23          23    0.021906                PTT
32          32    0.021669          PaO2_FiO2
36          36    0.021619               SpO2
20          20    0.021568                 Hb
5            5    0.021354          Weight_kg
26          26    0.020732               paO2
27          27    0.020035              paCO2
24          24    0.019899                 PT
38          38    0.019397         Creatinine
25          25    0.019374        Arterial_pH
29          29    0.019335   Arterial_lactate
14          14    0.019271          Potassium
40          40    0.019251               SGPT
19          19    0.019183            Calcium
39          39    0.019168               SGOT
28          28    0.018501        Arterial_BE
41          41    0.018380         Total_bili
15          15    0.018275             Sodium
16          16    0.018176           Chloride
30          30    0.017691               HCO3
18          18    0.016947          Magnesium
34          34    0.016659               SOFA
13          13    0.016497             FiO2_1
42          42    0.014688                INR
6            6    0.014160                GCS
2            2    0.013820           mechvent
35          35    0.008922               SIRS
3            3    0.007657     prev_dose_vaso
1            1    0.004696       re_admission
0            0    0.004569             gender

In [8]:
fi_rein_vaso_mimic

    featureNum  importance        featureName
45          45    0.046036       output_total
3            3    0.039690     prev_dose_vaso
37          37    0.036624                BUN
4            4    0.033583                age
43          43    0.032726        input_total
34          34    0.027990               SOFA
46          46    0.026865     output_4hourly
31          31    0.025699        Shock_Index
21          21    0.024926          WBC_count
9            9    0.024474             MeanBP
33          33    0.023790  cumulated_balance
7            7    0.023574                 HR
2            2    0.023013           mechvent
8            8    0.022234              SysBP
12          12    0.022215             Temp_C
11          11    0.022009                 RR
17          17    0.020993            Glucose
22          22    0.020980    Platelets_count
36          36    0.020980               SpO2
38          38    0.020736         Creatinine
23          23    0.020715                PTT
5            5    0.020689          Weight_kg
10          10    0.020433              DiaBP
44          44    0.020414      previous_dose
32          32    0.019918          PaO2_FiO2
20          20    0.019601                 Hb
24          24    0.019329                 PT
26          26    0.019051               paO2
30          30    0.018898               HCO3
29          29    0.018659   Arterial_lactate
19          19    0.018449            Calcium
25          25    0.018416        Arterial_pH
27          27    0.018342              paCO2
16          16    0.018294           Chloride
6            6    0.018055                GCS
15          15    0.017996             Sodium
28          28    0.017696        Arterial_BE
14          14    0.017692          Potassium
39          39    0.017130               SGOT
41          41    0.017011         Total_bili
40          40    0.017007               SGPT
18          18    0.015965          Magnesium
13          13    0.015947             FiO2_1
42          42    0.014750                INR
35          35    0.012564               SIRS
1            1    0.004092       re_admission
0            0    0.003751             gender

In [ ]:
def plot_pie_chart(fi_phys, fi_rein, title):
    fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(18, 7), dpi=300)

    cmap = plt.cm.get_cmap('Spectral')
    fi_phys['color'] = fi_phys['featureNum'].apply(lambda x: cmap(x/47))
    fi_rein['color'] = fi_rein['featureNum'].apply(lambda x: cmap(x/47))
    
    fig.suptitle('Feature Importance on Decision Tree Classifier for {}'.format(title), y=1.0, fontsize=16)

    axes[0].set_title('Physician', y=-.1)
    # axes[0].pie(fi_phys['importance'], labels=fi_phys['featureName'], autopct='%1.2f%%', pctdistance=0.85, shadow=False, startangle=90)
    axes[0].pie(fi_phys['importance'], labels=fi_phys['featureName'], colors=fi_phys['color'], shadow=False, startangle=90)
    axes[0].axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.

    axes[1].set_title('AI', y=-.1)
    # axes[1].pie(fi_rein['importance'], labels=fi_rein['featureName'], autopct='%1.2f%%', pctdistance=0.85, shadow=False, startangle=90)
    axes[1].pie(fi_rein['importance'], labels=fi_rein['featureName'], colors=fi_rein['color'], shadow=False, startangle=90)
    axes[1].axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.

    fig.tight_layout()
    plt.show()

In [ ]:
plot_pie_chart(fi_phys_iv_mimic, fi_rein_iv_mimic, "IV (MIMIC)")
plot_pie_chart(fi_phys_vaso_mimic, fi_rein_vaso_mimic, "Vasopressor (MIMIC)")

plot_pie_chart(fi_phys_iv_eicu, fi_rein_iv_eicu, "IV (eICU)")
plot_pie_chart(fi_phys_vaso_eicu, fi_rein_vaso_eicu, "Vasopressor (eICU)")